<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Delicious Bakery</title>';
echo '';
echo '<link rel="stylesheet" href="css/navStyle.css">';
echo '</head>';
echo '<body style="background-image: url(images/pastry/background.avif);"></body>';
echo '<div class="topnav">';
echo '<a href="./">Home</a>';
echo '<a href="about.html">About us</a>';
echo '<a href="menu.html">Menu</a>';
echo '<a href="contact.html">Contact Us</a>';
echo '';
echo '<div class="topnav-right">';
echo '<a href="myaccount.html">Sign Up</a>';
echo '</div>';
echo '</div>';
echo '<header>';
echo '<p style="';
echo 'font-size: larger;';
echo '">| Your one-stop destination for mouthwatering treats! |</p>';
echo '<h1>Welcome to Delicious Bakery</h1>';
echo '';
echo '</header>';
print '<img src="images/pastry/Baker.jpg" width="20%"/> <img src="images/pastry/Queen cakes.jpg" width="20%"/>';
echo '<section id="menu">';
echo '<h2>Our Menu</h2>';
echo '<p>Explore our delectable range of pastries, cakes, and breads.</p>';
echo '<!-- Add menu items and descriptions here -->';
echo '</section>';
echo '';
echo '<section id="about">';
echo '<h2>About Us</h2>';
echo '<p>We are passionate bakers committed to delivering quality and flavor.</p>';
echo '<!-- Add more details about your bakery -->';
echo '</section>';
echo '';
echo '<section id="contact">';
echo '<h2>Contact Us</h2>';
echo '<p>Reach out to us for orders, inquiries, or just to say hello!</p>';
echo '<!-- Include contact information and a contact form -->';
echo '</section>';
echo '</body>';
echo '</html>';
?>