<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Menu</title>';
echo '';
echo '<style>';
echo 'table{';
echo 'border:solid 1px #373737;';
echo 'width: 70%;';
echo 'border-collapse: collapse;';
echo '}';
echo 'td{';
echo 'border: solid 1px #373737;';
echo 'padding: 5px;';
echo 'text-align: left;';
echo '}';
echo 'th{';
echo 'background-color: rgba(0, 0,0,90%);';
echo 'color: rgba(255,255,255,90%);';
echo '}';
echo 'tr:nth-child(odd){';
echo 'background-color: beige;';
echo '}';
echo 'tr:hover{';
echo 'background-color: grey;';
echo '}';
echo '</style>';
echo '<link rel="stylesheet" href="css/navStyle.css">';
echo '</head>';
echo '<body style="background-image: url(images/pastry/background.avif);"></body>';
echo '<div class="topnav">';
echo '<a href="./">Home</a>';
echo '<a href="about.html">About us</a>';
echo '<a href="menu.html">Menu</a>';
echo '<a href="contact.html">Contact Us</a>';
echo '';
echo '<div class="topnav-right">';
echo '<a href="myaccount.html">Sign Up</a>';
echo '</div>';
echo '</div>';
echo '<section id="menu">';
echo '<h2>Our Menu</h2>';
echo '<p>Explore our delectable range of pastries, cakes, and breads.</p>';
echo '<ul>';
echo '<li>';
echo '<h3>Cupcakes</h3>';
echo '<p>Choose from a variety of flavors: chocolate, vanilla, red velvet, and more.</p>';
echo '</li>';
echo '<li>';
echo '<h3>Pastries</h3>';
echo '<p>Indulge in flaky croissants, Danish pastries, and fruit turnovers.</p>';
echo '</li>';
echo '<li>';
echo '<h3>Cakes</h3>';
echo '<p>Customize your celebration cake: birthday, wedding, or special occasion.</p>';
echo '</li>';
echo '<li>';
echo '<h3>Breads</h3>';
echo '<p>Freshly baked baguettes, whole wheat loaves, and sourdough.</p>';
echo '</li>';
echo '</ul>';
echo '<table >';
echo '<tr>';
echo '<th>SN</th>';
echo '<th>Item Name</th>';
echo '<th>Quantity</th>';
echo '<th>Price</th>';
echo '</tr>';
echo '<tr>';
echo '<td>1.</td>';
echo '<td>Orange cake</td>';
echo '<td>2 KG</td>';
echo '<td>3000 ksh</td>';
echo '</tr>';
echo '<tr>';
echo '<td>2.</td>';
echo '<td>Madeira Cake</td>';
echo '<td>3 KG</td>';
echo '<td>4000 ksh</td>';
echo '</tr>';
echo '<tr>';
echo '<td>3.</td>';
echo '<td>Vanilla cake</td>';
echo '<td>1Kg</td>';
echo '<td>2500 ksh</td>';
echo '</tr>';
echo '<tr>';
echo '<td>4.</td>';
echo '<td>red velvet</td>';
echo '<td>3 KG</td>';
echo '<td>5500 ksh</td>';
echo '</tr>';
echo '</table>';
echo '</section>';
echo '';
echo '</body>';
echo '</html>';
?>